In [1]:
import numpy as np

matriz = np.zeros([10,15], dtype=int)
#criando a matriz com zeros

In [2]:
from operator import index


class table:
    def __init__(self, ini_row, Ini_col, fim_row, fim_col, matrix):
        
        self.ini_row = ini_row 
        self.ini_col = Ini_col
        self.fim_row = fim_row
        self.fim_col = fim_col
        self.total_rows = fim_row - ini_row
        self.total_cols = fim_col - Ini_col 
        self.matrix = matrix

    #seta o inicio e fim
    def put_iniEfim(self):
        self.matrix[self.ini_row,self.ini_col] = 1
        self.matrix[self.fim_row,self.fim_col] = -1
    
    #obstaculos aleatoriamente
    def init_obstacles(self):
        local_x_list = []#lista das x cordenadas aleatórias
        local_y_list = []
        quantd = int((self.total_cols*self.total_rows)*0.3)  #30% de obstaculos
        rng = np.random.default_rng()

        local_x_list = rng.integers(self.ini_row, self.fim_row+1,quantd)
        local_y_list = rng.integers(self.ini_col+1,self.fim_col,quantd)
        
        obstacles = []
        #organiza lista de cordenadas
        for index,x in enumerate(local_x_list):
            item = [x,local_y_list[index]] #]str(x)+','+str(local_y_list[index])
            obstacles.append(item)

        for o in obstacles:
            self.matrix[o[0],o[1]] = 2

        print(self.matrix)
        
        # print(obstacles[0][1]) forma de acesso

In [3]:
# 1 marca o inicio
#-1 é o final
# 2 são obstaculos
# 3 são caminhos visitados

main_table = table(0,1,9,12,matriz)
main_table.put_iniEfim()
main_table.init_obstacles()

[[ 0  1  0  2  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  2  0  0  0  0]
 [ 0  0  0  2  2  2  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  2  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  2  2  0  2  2  2  0  0  0  0  0  0  0]
 [ 0  0  2  0  2  2  2  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  2  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  2  0  0  0  2  2  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0]]


In [4]:

class map_grid:
    def __init__(self,matrix,mr,mc):
        self.x = 0
        self.y = 0
        self.matrix = matrix
        self.pixel = self.matrix[self.x,self.y]
        self.vizinho = []
        self.max_row = mr
        self.max_col = mc

    def put_local(self,x,y):
        self.x = x
        self.y = y
        self.pixel = self.matrix[x,y]

    #verifica um possivel estouro de linhas e colunas
    def is_overflow(self):
        x = self.x
        y = self.y
        return x+1 >= self.max_row or y+1 >= self.max_col
    #é um obstaculo?
    def is_obstacle(self,x,y):
        return self.matrix[x,y] == 2
    #já foi visitado?
    def is_visited(self,x,y):
        return self.matrix[x,y] == 3
    #chegou no final?
    def is_final(self):
        return self.pixel == -1
    #define a rota
    def rota(self):
        x = self.x
        y = self.y
        #esquerda
        # não utrapasse linha ou col, não seja obstaculo e não seja visitado
        if  not self.is_overflow() and not self.is_obstacle(x,y+1) and not self.is_visited(x,y+1):
            
            self.vizinho.append([x,y+1]) #cordenadas do vizinho
            print(self.vizinho)

        #direita 
        if self.y > -1 and not self.is_obstacle(x,y-1) and not self.is_visited(x,y-1):
            self.vizinho.append([x,y-1])
        
        #cima
        if  x-1 > -1 and not self.is_obstacle(x-1,y) and not self.is_visited(x-1,y): 
            self.vizinho.append([x-1,y])

        #baixo
        if not self.is_overflow() and not self.is_obstacle(x+1,y) and not self.is_visited(x+1,y): 
            self.vizinho.append([x+1,y+1])

In [5]:
row = main_table.ini_row
col = main_table.ini_col

mapa = map_grid(main_table.matrix ,main_table.total_rows+1 ,main_table.total_cols+1)

mapa.put_local(row,col)
mapa.rota()

[[0, 2]]


In [ ]:
class a_star:
    



In [ ]:

#loop 
while(true):
    break