In [1]:
import numpy as np

matriz = np.zeros([20,15], dtype=int)
#criando a matriz com zeros

In [2]:
ini = [4,3]
fim = [16,10]
matriz[ini[0],ini[1]]= 1
matriz[fim[0],fim[1]] = -1
print(matriz)
#testando acesso e valor
#definindo inicio e fim hardcode

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 -1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [3]:
rng = np.random.default_rng()

id_ini = int(str(ini[0]) + str(ini[1]))
id_fim = int(str(fim[0]) + str(fim[1]))

print(id_ini,'+',id_fim)

tam_coluna = fim[1]-ini[1]
tam_lina = fim[0]-ini[0]


espaco = int((tam_coluna*tam_lina)*0.3)

int((id_fim-id_ini *0.5))
#print(espaco)

blocos = rng.integers(id_ini, id_fim,espaco )
print(blocos)

#checar os numeros aleatorios
#checar quantidade de blocos gerados
#passar para string
#e selecionar numeros de 2 a 4 casas

43 + 1610
[ 124  748  420 1317  157  420 1257  799  533 1166 1078  422 1454  588
  310 1220   61  538 1127  259  736 1000  998  486 1566]


In [5]:
# def filt(x):
#     if len(str(x)) != 3:
#         return x
    
obstaculos = []


for i in blocos:
    var = str(i)
    size = len(var) 
    if size != 3:
        if size == 2:
            obstaculos.append([int(var[0]),int(var[1])])
        else:
            obstaculos.append([int(var[0:2]),int(var[2:4])])

#criando lista de obstáculos
print(obstaculos)

[[13, 17], [12, 57], [11, 66], [10, 78], [14, 54], [12, 20], [6, 1], [11, 27], [10, 0], [15, 66]]


In [60]:
print(id_ini,'+',id_fim)

11 + 42


In [ ]:
#inicia o jogo
def init(matriz,obstaculos,partida,fim):
    
    cordenadas_obs = [x_y:[0,0]]
    for i,j in matriz:
        
    
    